---
title: "Resoultion Mean and SD"
author: "Anna Talucci"
date: "8/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Objective
Assess standard deviations (SD) and there spread at each spatial resolution.


# Pakcages
```{r}
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
```

# Functions

```{r}
numextract <- function(string){ 
  str_extract(string, "\\-*\\d+\\.*\\d*")
} 

```

# Data
```{r}
gcc = read.csv("../data/extracted_data/gcc_all_sd.csv")
```


```{r}
head(gcc)
```
mutate(gradebook, letter = ifelse(grade %in% 60:69, "D",
                                     ifelse(grade %in% 70:79, "C",
                                            ifelse(grade %in% 80:89, "B",
                                                   ifelse(grade %in% 90:99, "A", "F")))))
```{r}
gcc1 = gcc %>%
  pivot_longer(-ID, names_to = "buffer", values_to = "sd") %>%
  mutate(buf_res = numextract(buffer)) %>%
  mutate(res_meters = ifelse(buf_res %in% 25, "25cm",
                                    ifelse(buf_res %in% 50, "50cm",
                                    ifelse(buf_res %in% 1, "1m",
                                    ifelse(buf_res %in% 3, "3m",
                                    ifelse(buf_res %in% 5, "5m", "10m")))))) %>%
  mutate(res_meters = factor(res_meters, levels = c("25cm", "50cm", "1m", "3m", "5m", "10m")))
head (gcc1)
```


```{r}
ndvi = read.csv("../data/extracted_data/2020-08-18_ndvi_all_sd.csv")
```


```{r}
head(ndvi)
```

```{r}
ndvi1 = ndvi %>%
  pivot_longer(-ID, names_to = "buffer", values_to = "sd") %>%
  mutate(buf_res = numextract(buffer)) %>%
  mutate(res_meters = ifelse(buf_res %in% 25, "25cm",
                                    ifelse(buf_res %in% 50, "50cm",
                                    ifelse(buf_res %in% 1, "1m",
                                    ifelse(buf_res %in% 3, "3m",
                                    ifelse(buf_res %in% 5, "5m", "10m")))))) %>%
  mutate(res_meters = factor(res_meters, levels = c("25cm", "50cm", "1m", "3m", "5m", "10m")))
head (ndvi1)
```


# Define graph Theme and color Palette 

```{r}
comp_theme = theme_bw() + theme(legend.position = "none") +  
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        axis.line = element_line(colour = "black"))
```
 
```{r}

reg_theme = theme_bw() + theme(legend.position = "none") +
  theme(plot.margin = unit(c(t = 0.3, r = 0.3, b = 0.3, l = 0.1), "cm")) +
  theme(axis.title.x = element_text(size = 11, hjust = 0.5, vjust = -0.1),
        axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))

```

```{r}
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```



# Data visualization



## GCC
```{r fig.height=4, fig.width=6}
plot_gcc = ggplot(data = gcc1, aes(x = res_meters , y = sd, color = res_meters)) +
  geom_boxplot() +       
  geom_point() +
         scale_color_manual(values=cbbPalette) +
          ylab("Standard deviation GCC") +
          xlab("")  +
           comp_theme +
  guides(color=guide_legend(override.aes=list(fill=NA), title = "GCC"))

plot_gcc
```
```{r eval=FALSE, include=FALSE}
ggsave("../figures/2020-08-19_gcc-SD-resolution.jpeg", plot = plot_gcc, width = 6, height = 4, units = c("in"), dpi=600 )
```

```{r fig.height=4, fig.width=6}
plot_ndvi = ggplot(data = ndvi1, aes(x = res_meters , y = sd, color = res_meters)) +
  geom_boxplot() +       
  geom_point() +
         scale_color_manual(values=cbbPalette) +
          ylab("sd NDVI") +
          xlab("")  +
           ylab("Standard deviation NDVI") +
          xlab("")  +
           comp_theme 

plot_ndvi
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/2020-08-19_ndvi-SD-resolution.jpeg", plot = plot_ndvi, width = 6, height = 4, units = c("in"), dpi=600 )
```

```{r fig.height=7, fig.width=6}

grid1 = cowplot::plot_grid(plot_gcc, plot_ndvi, labels = "AUTO", align = "hv", label_size = 12, ncol= 1)  
  
grid1
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/2020-08-20_SD-ndvi-gcc.jpeg", plot = grid1, width = 6, height = 7, units = c("in"), dpi=600 )
```