---
title: "Field and UAv Data Analysis"
author: "Anna Talucci"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pakcages
```{r}
library(tidyr)
library(dplyr)
```


# Field Data
```{r}
sites = read.csv("../data/field_subset/site_info_uav.csv")
shrubs = read.csv("../data/field_subset/shrub_info_uav.csv")
trees = read.csv("../data/field_subset/tree_info_uav.csv")
```

```{r}
sites
```

## field Plot sizes

```{r}
shrubs %>% group_by(site, transect) %>% 
  summarise(min(area_sampled_m2))
```

```{r}
shrubs %>% group_by(site, transect) %>% 
  summarise(max(area_sampled_m2))
```

```{r}
trees %>% group_by(site, transect) %>% 
  summarise(min(radius))
```

```{r}
trees %>% group_by(site, transect) %>% 
  summarise(max(radius))
```

# UAV Data

```{r}
gcc_1m = read.csv("../data/extracted_data/gcc_1m.csv", strip.white = TRUE)
gcc_3m = read.csv("../data/extracted_data/gcc_3m.csv", strip.white = TRUE)
gcc_25cm = read.csv("../data/extracted_data/gcc_25cm.csv", strip.white = TRUE)
ndvi_1m = read.csv("../data/extracted_data/ndvi_1m.csv", strip.white = TRUE)
ndvi_3m = read.csv("../data/extracted_data/ndvi_3m.csv", strip.white = TRUE)
ndvi_25cm = read.csv("../data/extracted_data/ndvi_25cm.csv", strip.white = TRUE)
```

```{r}
gcc_1m
```

```{r}
gcc_3m
```

```{r}
gcc_25cm
```
```{r}
summary(gcc_25cm)
```

## Combine GCC data

```{r}
gcc_merge1 = merge(gcc_1m, gcc_3m,  by= "ID")
gcc_merge1
gcc = merge(gcc_merge1, gcc_25cm,  by="ID")
gcc
```


# Combine Field and UAV
