---
title: "UAV-Biomass-Explore"
author: "Anna Talucci"
date: "8/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r eval=FALSE, include=FALSE}
install.packages(c('aomisc'),
lib='C:/Users/atalucci/Documents/R/win-library/3.6')

install.packages("remotes")
remotes::install_github("OnofriAndreaPG/aomisc")

```



# Pakcages
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(stringr)
library(lme4)
library(cowplot)
library(lme4)
library(lsmeans)
library(DHARMa)
library(rcompanion)
library(qpcR)
library(tidyverse)
library(aomisc)
```

# Functions

```{r}
numextract <- function(string){ 
  str_extract(string, "\\-*\\d+\\.*\\d*")
} 

```

# Field Data
```{r}
field_data = read.csv("../data/field_subset/field_data_all.csv")
```

```{r}
head(field_data)
```

## field Plot sizes

```{r}
field_data %>% group_by(site, transect) %>% 
  summarise(min(shrub_plot_area))
```

```{r}
field_data %>% group_by(site, transect) %>% 
  summarise(max(shrub_plot_area))
```

```{r}
field_data %>% group_by(site, transect) %>% 
  summarise(min(tree_radius))
```

```{r}
field_data %>% group_by(site, transect) %>% 
  summarise(max(tree_radius))
```

# UAV Data

```{r}
gcc_all = read.csv("../data/extracted_data/gcc_all.csv", strip.white = TRUE)
ndvi_all = read.csv("../data/extracted_data/2020-08-10_ndvi_all_pix4D.csv", strip.white = TRUE)
```

```{r}
head(gcc_all)
head(ndvi_all)
```
# Pull out GCC and NDVI by buffer size

```{r}
gcc_long = gcc_all %>% 
  dplyr::select(ID:mean_gcc_10m) %>%
  pivot_longer(-ID, names_to = "buffer", values_to = "gcc") %>%
  mutate(buf_res = numextract(buffer))

gcc_long
```

```{r}
ndvi_long = ndvi_all %>% 
  dplyr::select(ID:mean_ndvi_10m) %>%
  pivot_longer(-ID, names_to = "buffer", values_to = "ndvi") %>%
  mutate(buf_res = numextract(buffer))

ndvi_long
```

# Combine Field and UAV data

```{r}
gcc_ndvi = merge(gcc_all, ndvi_all, by="ID")
gcc_ndvi
field_gcc = merge(field_data, gcc_all, by="ID") 
field_gcc
field_gcc_ndvi = merge(field_data, gcc_ndvi,  "ID")
field_gcc_ndvi
```
# Field data +  long data
```{r}
field_gcc_long = merge(field_data, gcc_long, by="ID")

field_gcc_long
```

```{r}
field_ndvi_long = merge(field_data, ndvi_long, by="ID")

field_ndvi_long
```

# Variables as factor

```{r}
field_gcc$burn_year = as.factor(field_gcc$burn_year)
field_gcc_ndvi$burn_year = as.factor(field_gcc_ndvi$burn_year)

str(field_gcc)
str(field_gcc_ndvi)
```

```{r}
field_gcc_long$burn_year = as.factor(field_gcc_long$burn_year)
field_ndvi_long$burn_year= as.factor(field_ndvi_long$burn_year)
field_gcc_long$buf_res = as.factor(field_gcc_long$buf_res)
field_ndvi_long$buf_res = as.factor(field_ndvi_long$buf_res)
```

## Exploratory plots
```{r}
head(field_gcc)
head(field_gcc_ndvi)
```
```{r}
field_gcc1 = field_gcc %>% dplyr::select(ID:aspect, live_woody_biomass_C_g_m, mean_gcc_25cm:mean_gcc_10m)

head(field_gcc1)
```

### gcc and biomass
```{r}

set.seed(16)
#dat = data.frame(elev = round( runif(20, 100, 500), 1),
                # resp = round( runif(20, 0, 10), 1),
                # grad = round( runif(20, 0, 1), 2),
                # slp = round( runif(20, 0, 35),1),
                # lat = runif(20, 44.5, 45),
                # long = runif(20, 122.5, 123.1),
                # nt = rpois(20, lambda = 25) )
#head(dat)

response = names(field_gcc1)[12]
expl = names(field_gcc1)[13:18]

response = purrr::set_names(response)
response

expl = purrr::set_names(expl)
expl

scatter_fun = function(x, y) {
     ggplot(field_gcc1, aes(x = .data[[x]], y = .data[[y]]) ) +
          geom_point() +
          geom_smooth(method = "loess", se = FALSE, color = "grey74") +
          theme_bw() +
          labs(x = x,
               y = y)
}

scatter_fun = function(x, y) {
     ggplot(field_gcc1, aes_string(x = x, y = y ) ) +
          geom_point() +
          geom_smooth(method = "loess", se = FALSE, color = "grey74") +
          theme_bw() 
}

#scatter_fun("lat", "elev")

#elev_plots = map(expl, ~scatter_fun(.x, "elev") )
#elev_plots

all_plots = map(response,
                ~map(expl, scatter_fun, y = .x) )

#all_plots$grad[1:2]
#all_plots$grad$long
#all_plots[[3]][[3]]


cowplot::plot_grid(plotlist = all_plots[[1]])

response_plots = map(all_plots, ~cowplot::plot_grid(plotlist = .x))
response_plots
```

### ndvi and biomass
```{r}
field_gcc_ndvi1 = field_gcc_ndvi %>% dplyr::select(ID:aspect, live_woody_biomass_C_g_m, mean_gcc_25cm:mean_gcc_10m, mean_ndvi_25cm:mean_ndvi_10m)

head(field_gcc_ndvi1)
```

```{r}

set.seed(16)


response = names(field_gcc_ndvi1)[12]
expl = names(field_gcc_ndvi1)[13:24]

response = purrr::set_names(response)
response

expl = purrr::set_names(expl)
expl

scatter_fun = function(x, y) {
     ggplot(field_gcc_ndvi1, aes(x = .data[[x]], y = .data[[y]]) ) +
          geom_point() +
          geom_smooth(method = "loess", se = FALSE, color = "grey74") +
          theme_bw() +
          labs(x = x,
               y = y)
}

scatter_fun = function(x, y) {
     ggplot(field_gcc_ndvi1, aes_string(x = x, y = y ) ) +
          geom_point() +
          geom_smooth(method = "loess", se = FALSE, color = "grey74") +
          theme_bw() 
}



all_plots = map(response,
                ~map(expl, scatter_fun, y = .x) )

pdf("../figures/2020-08-17_explore-biomass.pdf")
all_plots
dev.off()


cowplot::plot_grid(plotlist = all_plots[[1]])

response_plots2 = map(all_plots, ~cowplot::plot_grid(plotlist = .x))
response_plots2
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/2020-08-17_explore-biomass.jpeg", plot = response_plots2, width = 12, height = 12, units = c("in"), dpi=600 )
```


### NDVI biomass bunr only
```{r}
field_gcc_ndvi2 = field_gcc_ndvi %>% dplyr::select(ID:aspect, live_woody_biomass_C_g_m, mean_ndvi_25cm:mean_ndvi_10m) %>% filter(burn_unburn == "burned")

head(field_gcc_ndvi2)
```

```{r}

set.seed(16)


response = names(field_gcc_ndvi1)[12]
expl = names(field_gcc_ndvi1)[13:18]

response = purrr::set_names(response)
response

expl = purrr::set_names(expl)
expl

scatter_fun = function(x, y) {
     ggplot(field_gcc_ndvi2, aes(x = .data[[x]], y = .data[[y]]) ) +
          geom_point() +
          geom_smooth(method = "loess", se = FALSE, color = "grey74") +
          theme_bw() +
          labs(x = x,
               y = y)
}

scatter_fun = function(x, y) {
     ggplot(field_gcc_ndvi2, aes_string(x = x, y = y ) ) +
          geom_point() +
          geom_smooth(method = "loess", se = FALSE, color = "grey74") +
          theme_bw() 
}



all_plots = map(response,
                ~map(expl, scatter_fun, y = .x) )


cowplot::plot_grid(plotlist = all_plots[[1]])

response_plots = map(all_plots, ~cowplot::plot_grid(plotlist = .x))
response_plots
```

# Logistic regression

```{r}
model <- drm(live_woody_biomass_C_g_m ~ mean_ndvi_10m, fct = L.3(), data = field_gcc_ndvi1)
summary(model)
```

```{r}
plot(model, log="", main = "Logistic function")
```

